import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en' | 'az';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  tr: {
    'header.services': 'Hizmetlerimiz',
    'header.help': 'Yardım',
    'header.account': 'Hesabım',
    'header.login': 'Giriş Yap',
    'header.register': 'Kayıt Ol',
    'header.contact': 'İletişim',
    'header.customerService': '7/24 Müşteri Hizmetleri',
    'header.whatsapp': 'WhatsApp',
    'header.instantSupport': 'Anında destek',
    'header.aboutUs': 'Hakkımızda',
    'header.emailLabel': 'E-posta',
    'header.customerPanel': 'Müşteri Paneli',
    'header.logout': 'Çıkış',
    'header.whereToGo': 'Nereye gitmek istiyorsunuz?',
    'header.date': 'Tarih',
    'header.guest': 'Konuk',
    'header.search': 'Ara',
    'hero.title': "Azerbaycan'ın Seyahat Sitesi",
    'hero.flight': 'Uçak bileti',
    'hero.hotel': 'Otel',
    'hero.tour': 'Tur',
    'hero.bus': 'Otobüs',
    'hero.carRental': 'Araç kiralama',
    'hero.transfer': 'Transfer',
    'hero.oneWay': 'Tek yön',
    'hero.roundTrip': 'Gidiş-dönüş',
    'hero.multiCity': 'Çoklu uçuş',
    'hero.nonStop': 'Aktarmasız',
    'hero.from': 'Nereden',
    'hero.to': 'Nereye',
    'hero.departDate': 'Gidiş Tarihi',
    'hero.addReturn': 'Dönüş Ekle',
    'hero.passengers': 'Yolcu',
    'hero.passenger': 'Yolcu',
    'hero.economy': 'Ekonomi',
    'hero.findCheapTicket': 'Ucuz bilet bul',
    'hero.listHotels': 'Bu tarihler için otelleri de listele',
    'hero.cabinEconomy': 'Ekonomi',
    'hero.cabinPremium': 'Premium',
    'hero.cabinBusiness': 'Business',
    'hero.cabinFirst': 'Birinci',
    'hero.departureCity': 'Çıkış Şehri',
    'hero.selectCity': 'Şehir seçin',
    'hero.country': 'Ülke',
    'hero.selectCountry': 'Ülke seçin',
    'hero.airline': 'Havayolu',
    'hero.allAirlines': 'Hepsi',
    'hero.guests': 'Konuklar',
    'hero.guest': 'Konuk',
    'hero.departureFrom': 'Gidiş',
    'hero.departureTo': 'Gidiş Son',
    'hero.nightsMin': 'Gece (Min)',
    'hero.nightsMax': 'Gece (Maks)',
    'hero.night': 'gece',
    'hero.searchTour': 'Tur Ara',
    'hero.cheapest': 'En Ucuz',
    'hero.fastest': 'En Hızlı',
    'hero.more': 'Daha Fazla',
    'hero.resultsFound': 'sonuç bulundu',
    'hero.closeResults': 'Sonuçları kapat',
    'hero.adult': 'Yetişkin',
    'hero.child': 'Çocuk',
    'hero.childAge': 'Çocuk yaşı',
    'hero.addChild': 'Çocuk ekle',
    'hero.apply': 'Uygula',
    'hero.flightDetails': 'Uçuş detayları',
    'hero.outbound': 'Gidiş',
    'hero.return': 'Dönüş',
    'hero.selectFlight': 'Bu uçuşu seç',
    'hero.directFlight': 'Direkt Uçuş',
    'hero.stopover': 'Aktarma',
    'hero.sponsored': 'Sponsorlu',
    'hero.businessClass': 'Business Class',
    'datePicker.title': 'Giriş ve Çıkış Tarihi',
    'datePicker.checkIn': 'Giriş Tarihi',
    'datePicker.checkOut': 'Çıkış Tarihi',
    'datePicker.guests': 'Konuk Sayısı',
    'datePicker.adults': 'Yetişkin',
    'datePicker.room': 'Oda',
    'datePicker.calendarSearch': 'Takvimde Ara',
    'datePicker.holidays': 'Resmi Tatiller',
    'datePicker.apply': 'Uygula',
    'datePicker.holidaysComingSoon': 'Resmi tatil günleri yakında eklenecek...',
    'day.mon': 'Pts', 'day.tue': 'Sal', 'day.wed': 'Çar', 'day.thu': 'Per', 'day.fri': 'Cum', 'day.sat': 'Cts', 'day.sun': 'Paz',
    'month.january': 'Ocak', 'month.february': 'Şubat', 'month.march': 'Mart', 'month.april': 'Nisan', 'month.may': 'Mayıs', 'month.june': 'Haziran', 'month.july': 'Temmuz', 'month.august': 'Ağustos', 'month.september': 'Eylül', 'month.october': 'Ekim', 'month.november': 'Kasım', 'month.december': 'Aralık',
    'deals.title': 'Fırsat uçuşları',
    'deals.newYear': 'Yılbaşı Fırsatları',
    'deals.international': 'Yurt dışı',
    'deals.domestic': 'Yurt içi',
    'deals.viewAll': 'Tümünü gör',
    'destinations.title': 'Popüler Destinasyonlar',
    'destinations.exploreAll': 'Tümünü Keşfet',
    'destinations.from': 'başlayan fiyatlarla',
    'destinations.subtitle': 'En çok seçilen destinasyonları keşfedin ve unutulmaz anılar biriktirin',
    'destinations.hotelOptions': 'otel seçeneği',
    'destinations.lowest': 'En düşük',
    'destinations.explore': 'Keşfet',
    'hotels.title': 'Öne Çıkan Oteller',
    'hotels.viewAll': 'Tüm Otelleri Gör',
    'hotels.night': 'gece',
    'hotels.from': 'dan başlayan fiyatlarla',
    'hotels.rating': 'Değerlendirme',
    'hotels.reviews': 'yorum',
    'hotels.bookNow': 'Hemen Rezervasyon Yap',
    'hotels.mostPopular': 'En Popüler',
    'hotels.new': 'Yeni',
    'hotels.discount': 'İndirim',
    'hotels.wifi': 'Wifi',
    'hotels.parking': 'Otopark',
    'hotels.restaurant': 'Restoran',
    'hotels.pool': 'Havuz',
    'hotels.perNight': 'gecelik',
    'hotels.maxxRoyalDesc': 'Lüks golf resort ile unutulmaz bir tatil deneyimi',
    'hotels.titanicDesc': 'Muhteşem saray mimarisi ve lüks hizmet',
    'hotels.voyageDesc': 'Golf ve spa ile mükemmel bir kombinasyon',
    'hotels.delphinDesc': 'Aile dostu ultra her şey dahil resort',
    'campaigns.title': 'Özel Kampanyalar',
    'campaigns.subtitle': 'Sınırlı süreli özel tekliflerden yararlanın ve hayalinizdeki tatili uygun fiyatlarla yakalayın',
    'campaigns.viewAll': 'Tümünü Gör',
    'campaigns.upTo': "e varan",
    'campaigns.discount': 'indirim',
    'campaigns.details': 'Detayları Gör',
    'campaigns.explore': 'Keşfet',
    'campaigns.until': 'tarihine kadar',
    'campaigns.summer': 'Yazın Son Fırsatları',
    'campaigns.summerDesc': '%40 indirimle tatil keyfi',
    'campaigns.earlyBird': 'Erken Rezervasyon',
    'campaigns.earlyBirdDesc': '2026 yazı için özel fiyatlar',
    'campaigns.romantic': 'Çiftler İçin Romantik',
    'campaigns.romanticDesc': 'Balayı paketlerinde büyük indirim',
    'campaigns.limitedTime': 'Sınırlı Süre',
    'campaigns.specialPrice': 'Özel Fiyat',
    'campaigns.romanticBadge': 'Romantik',
    'campaigns.notifications': 'Özel Kampanya Bildirimleri',
    'campaigns.notificationsDesc': 'Yeni fırsatlardan ilk sen haberdar ol',
    'campaigns.subscribe': 'Abone Ol',
    'campaigns.august31': '31 Ağustos',
    'campaigns.september15': '15 Eylül',
    'campaigns.september10': '10 Eylül',
    'earlyBooking.title': 'Erken Rezervasyon Fırsatları',
    'earlyBooking.saveUpTo': "e varan tasarruf",
    'earlyBooking.bookNow': 'Hemen Rezerve Et',
    'earlyBooking.benefit1Title': 'En İyi Fiyat Garantisi',
    'earlyBooking.benefit1Desc': 'Erken rezervasyonla en uygun fiyatları elde edin',
    'earlyBooking.benefit2Title': 'Ücretsiz İptal',
    'earlyBooking.benefit2Desc': '7 gün öncesine kadar ücretsiz iptal hakkı',
    'earlyBooking.benefit3Title': 'Güvenli Ödeme',
    'earlyBooking.benefit3Desc': '256-bit SSL şifreleme ile güvenli ödeme',
    'earlyBooking.benefit4Title': '7/24 Destek',
    'earlyBooking.benefit4Desc': 'Profesyonel ekibimiz her zaman yanınızda',
    'earlyBooking.heading1': '2026 Yazını Şimdiden',
    'earlyBooking.heading2': 'Planla ve Kazan!',
    'earlyBooking.description': 'Erken rezervasyon yaparak hem en iyi otelleri garantiye alın, hem de bütçenizi koruyun. Hayalinizdeki tatil için şimdi harekete geçin!',
    'earlyBooking.bookBtn': 'Erken Rezervasyon Yap',
    'earlyBooking.campaignsBtn': 'Kampanyalara Bak',
    'earlyBooking.discountLabel': 'Erken Rezervasyon İndirimi',
    'earlyBooking.happyCustomers': 'Mutlu Müşteri',
    'blog.title': 'Blog',
    'blog.readMore': 'Devamını Oku',
    'blog.allArticles': 'Tüm Yazılar',
    'blog.subtitle': 'Tatil deneyiminizi zenginleştiren rehberler, ipuçları ve keşif önerileri',
    'blog.post1Title': "Antalya'da Görmeniz Gereken 10 Yer",
    'blog.post1Excerpt': "Akdeniz'in incisi Antalya'da tatilinizde mutlaka ziyaret etmeniz gereken tarihi ve doğal güzellikleri keşfedin.",
    'blog.post1Category': 'Tatil Rehberi',
    'blog.post2Title': 'Yazın En Güzel Kaçış Noktaları: Ege Kıyıları',
    'blog.post2Excerpt': 'Ege denizinin masmavi sularında kendinizi kaybetmeye hazır olun. En güzel koylar, tarihi mekanlar ve lezzet durakları.',
    'blog.post2Category': 'Keşfet',
    'blog.post3Title': 'Bütçeye Uygun Tatil Tavsiyeleri',
    'blog.post3Excerpt': 'Az bütçeyle çok keyif! Cebinizi yakmadan unutulmaz tatil deneyimleri yaşamanın sırları.',
    'blog.post3Category': 'İpuçları',
    'blog.minutes': 'dakika',
    'reviews.title': 'Müşteri Yorumları',
    'reviews.whatTheySay': 'Müşterilerimiz Ne Diyor',
    'reviews.weeksAgo': 'hafta önce',
    'reviews.happyReviews': 'Mutlu Müşteri Yorumu',
    'reviews.satisfaction': 'Müşteri Memnuniyeti',
    'reviews.support': 'Müşteri Desteği',
    'reviews.bookings': 'Başarılı Rezervasyon',
    'reviews.experience': 'Yıllık Deneyim',
    'reviews.review1': "TourAgent ile yaptığım Antalya tatili harika oldu! Hem rezervasyon süreci çok kolay oldu, hem de önerilen otel beklentilerimizi aştı.",
    'reviews.review2': 'Aile olarak gittiğimiz Bodrum tatilinde her detay mükemmeldi. Çocuklar çok eğlendi, biz de dinlendik.',
    'reviews.review3': 'Balayımızı planlarken çok endişeliydik ama TourAgent ekibi bütün süreçte bize destek oldu. Romantik ve unutulmaz bir tatil geçirdik.',
    'footer.about': 'Hakkımızda',
    'footer.aboutUs': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.press': 'Basın',
    'footer.blog': 'Blog',
    'footer.support': 'Destek',
    'footer.helpCenter': 'Yardım Merkezi',
    'footer.termsOfService': 'Hizmet Şartları',
    'footer.privacy': 'Gizlilik',
    'footer.legal': 'Yasal',
    'footer.contact': 'İletişim',
    'footer.contactUs': 'Bize Ulaşın',
    'footer.partnerships': 'İş Ortaklıkları',
    'footer.affiliates': 'Bağlı Kuruluşlar',
    'footer.description': 'Azerbaycan\'ın en güvenilir seyahat platformu.',
    'footer.allRightsReserved': 'Tüm hakları saklıdır.',
    'footer.followUs': 'Bizi Takip Edin',
    'footer.newsletter': 'Özel Fırsatlardan Haberdar Olun',
    'footer.newsletterDesc': 'En iyi tatil fırsatları ve kampanyaları e-posta kutunuza gelsin',
    'footer.emailPlaceholder': 'E-posta adresinizi girin',
    'footer.companyDesc': '15 yıldır size en güzel tatil deneyimlerini sunmaktan gurur duyuyoruz. Hayalinizdeki tatil sadece bir tık uzağınızda.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.hotels': 'Oteller',
    'footer.flightTickets': 'Uçak Bileti',
    'footer.carRentalFooter': 'Araç Kiralama',
    'footer.activities': 'Aktiviteler',
    'footer.tourPackages': 'Tur Paketleri',
    'footer.lastMinuteDeals': 'Son Dakika Fırsatları',
    'footer.popularDestinations': 'Popüler Destinasyonlar',
    'footer.antalyaHotels': 'Antalya Otelleri',
    'footer.istanbulHotels': 'İstanbul Otelleri',
    'footer.bodrumHotels': 'Bodrum Otelleri',
    'footer.cappadociaHotels': 'Kapadokya Otelleri',
    'footer.cesmeHotels': 'Çeşme Otelleri',
    'footer.marmarisHotels': 'Marmaris Otelleri',
    'footer.customerServiceFooter': '7/24 Müşteri Hizmetleri',
    'footer.generalInfo': 'Genel Bilgi',
    'footer.refundPolicy': 'İade Politikası',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.termsConditions': 'Şartlar ve Koşullar',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'Size En İyi Seyahat Deneyimini Sunuyoruz',
    'services.whyChooseUs': 'Neden Bizi Seçmelisiniz?',
    'services.ourServices': 'Kapsamlı Hizmet Yelpazemiz',
    'services.whyUs': 'Neden TourAgent?',
    'services.viewDetails': 'Detaylı İncele',
    'services.happyCustomers': 'Mutlu Müşteri',
    'services.serviceTypes': 'Hizmet Türü',
    'services.countries': 'Ülke',
    'services.customerSupport': 'Müşteri Desteği',
    'services.comprehensiveRange': 'Kapsamlı Hizmet Çeşidimiz',
    'services.comprehensiveDesc': 'A\'dan Z\'ye seyahat ihtiyaçlarınız için tek durak çözümler',
    'services.whyChooseUsDesc': 'Müşteri memnuniyeti odaklı yaklaşımımızla fark yaratıyoruz',
    'services.securePayment': 'Güvenli Ödeme',
    'services.securePaymentDesc': '256-bit SSL şifreleme ile güvenli ödeme altyapısı',
    'services.bestPrice': 'En İyi Fiyat',
    'services.bestPriceDesc': 'Fiyat karşılaştırması ile en uygun seçenekleri sunuyoruz',
    'services.support247': '7/24 Destek',
    'services.support247Desc': 'Profesyonel ekibimiz her zaman yanınızda',
    'services.customers5000': '5000+ Müşteri',
    'services.customers5000Desc': 'Kısa sürede kazanılmış güven ve müşteri memnuniyeti',
    'services.ctaTitle': 'Seyahat Planlarınızı Bizimle Paylaşın',
    'services.ctaDesc': 'Profesyonel ekibimiz size özel seyahat paketleri hazırlamak için burada',
    'services.contactUs': 'Bize Ulaşın',
    'services.hotelBooking': 'Otel Rezervasyonu',
    'services.hotelBookingDesc': 'Dünyanın herhangi bir noktasında rahat ve konforlu konaklama için güvenilir otel rezervasyonu.',
    'services.flightTickets': 'Uçak Biletleri',
    'services.flightTicketsDesc': 'Uygun fiyatlarla herhangi bir yöne uçak bileti satışı ve uçuş desteği.',
    'services.tourPackages': 'Tur Paketleri',
    'services.tourPackagesDesc': 'Yurtiçi ve yurtdışı yönlerde çeşitli bireysel ve grup tur paketlerinin düzenlenmesi.',
    'services.honeymoon': 'Balayı Seyahatleri',
    'services.honeymoonDesc': 'Özel balayı programları ile aşkınızı daha da unutulmaz hale getirin.',
    'services.medicalTours': 'Termal Turlar',
    'services.medicalToursDesc': 'Sağlığınız için seçilmiş sanatoriyumlarda tedavi ve dinlenme turları.',
    'services.regionalTours': 'Bölge Turları',
    'services.regionalToursDesc': 'Azerbaycan\'ın en güzel bölgelerine konforlu ve eğlenceli turlar.',
    'services.schoolTours': 'Öğrenci Turları',
    'services.schoolToursDesc': 'Eğitim arası faydalı ve ilginç dinlenme programları öğrenciler için.',
    'services.visaSupport': 'Vize Desteği',
    'services.visaSupportDesc': 'Birçok ülkeye vize başvurusu ve belgelendirme konusunda tam destek.',
    'services.transferService': 'Transfer Hizmeti',
    'services.transferServiceDesc': 'Seyahat ettiğiniz ülkede standart ve VIP transfer hizmetleri.',
    'services.insurance': 'Sigorta',
    'services.insuranceDesc': 'Seyahatiniz boyunca güvenliğinizin teminatı için sigorta hizmetleri.',
    'about.since': 'dan beri',
    'about.title': 'Hakkımızda',
    'about.subtitle': 'TourAgent Travel – seyahatinizi gerçek uzmanına güvenin!',
    'about.happyCustomers': 'Mutlu Müşteri',
    'about.foundedYear': 'Kuruluş Yılı',
    'about.customerSupport': 'Müşteri Desteği',
    'about.countries': 'Ülke',
    'about.professionalTourism': 'Profesyonel Turizm',
    'about.servicesLabel': 'Hizmetlerimiz',
    'about.mainDesc1': 'TourAgent Travel 2022 yılında kurulmuş ve kısa sürede 5000\'den fazla müşteriye kaliteli seyahat hizmetleri sunan profesyonel bir turizm şirketidir.',
    'about.mainDesc2': 'Temel amacımız her müşterinin bütçesine, seçtiği tarihe ve seyahat ihtiyaçlarına uygun en doğru çözümü sunmaktır.',
    'about.affordableFlights': 'Uygun Uçak Bileti',
    'about.hotelBooking': 'Otel Rezervasyonu',
    'about.tourPackagesLabel': 'Tur Paketleri',
    'about.visaSupportLabel': 'Vize Desteği',
    'about.servicesDetail': 'Hizmetlerimiz Hakkında Detay',
    'about.servicesDetailDesc': 'Size en iyi seyahat deneyimini sunmak için geniş hizmet yelpazesi sunuyoruz',
    'about.flightService': 'Uçak Bileti Hizmeti',
    'about.flightServiceDesc': 'Her yöne en uygun uçak biletlerini kısa sürede bulur, uçuş öncesi tüm bilgileri detaylı şekilde sunarız.',
    'about.tourOrganization': 'Tur Paketi Düzenleme',
    'about.tourOrganizationDesc': 'Yurtiçi ve yurtdışı turlar, bireysel, grup ve aile turları, gençlik turları, tedavi turları, balayı turları ve özel gün turları düzenliyoruz.',
    'about.internationalTours': 'Yurtdışı Tur Paketleri',
    'about.internationalToursDesc': 'Yurtdışı tur paketlerinde 3 yıldızdan 5 yıldıza kadar otel seçenekleri sunarak müşterilerimizin rahat tatilini sağlıyoruz.',
    'about.specialTours': 'Özel Turlar',
    'about.specialToursDesc': 'Sağlık sorunları olan müşteriler için sanatoriyum programları, yeni evliler için balayı turları ve özel yılbaşı programları sunuyoruz.',
    'about.transferVip': 'Transfer ve VIP Hizmetler',
    'about.transferVipDesc': 'Standart ve VIP transfer hizmetlerimiz mevcuttur. Havalimanından otelinize güvenli ulaşımınızı sağlıyoruz.',
    'about.visaService': 'Vize Desteği',
    'about.visaServiceDesc': 'Uygun olduğunuz durumda vize almanız için tam destek sağlıyoruz. Belge hazırlamadan başvuru takibine kadar yanınızdayız.',
    'about.alwaysWithYou': 'Tüm hizmetlerimiz boyunca yanınızdayız',
    'about.alwaysWithYouDesc': 'Tüm hizmetlerimiz boyunca müşterilerimizle sürekli iletişim halinde olup 7/24 hizmetinizdeyiz.',
    'about.fastResponse': 'Hızlı Yanıt',
    'about.inMinutes': '5 dakika içinde',
    'about.secure': 'Güvenli',
    'about.sslEncryption': 'SSL şifreleme',
    'about.international': 'Uluslararası',
    'about.countriesPlus': '50+ ülke',
    'about.proTeam': 'Profesyonel Ekip',
    'about.experiencedStaff': 'Deneyimli kadro',
    'about.shareYourPlans': 'Seyahat planlarınızı bizimle paylaşın',
    'about.betterTravel': 'Daha kaliteli ve sorunsuz seyahat edin.',
    'about.trustAgent': 'TourAgent Travel – seyahatinizi gerçek uzmanına güvenin!',
    'about.contactInfo': 'İletişim Bilgileri',
    'about.contactAnytime': 'İstediğiniz zaman bizimle iletişime geçebilirsiniz',
    'about.address': 'Adres',
    'about.email': 'E-posta',
    'about.phone': 'Telefon',
    'about.whatsappLines': 'WhatsApp Hatlarımız',
    'about.writeOnWhatsapp': 'WhatsApp ile Yazın',
    'auth.memberLogin': 'Üye Girişi',
    'auth.registration': 'Kayıt Ol',
    'auth.loginToAccount': 'Hesabınıza giriş yapın',
    'auth.createAccount': 'Yeni hesap oluşturun',
    'auth.login': 'Giriş Yap',
    'auth.register': 'Kayıt Ol',
    'auth.fullName': 'Ad Soyad',
    'auth.emailAddress': 'E-posta Adresi',
    'auth.password': 'Şifre',
    'auth.forgotPassword': 'Şifrenizi mi unuttunuz?',
    'auth.loginBtn': 'Giriş Yap',
    'auth.registerBtn': 'Kayıt Ol',
    'auth.noAccount': 'Hesabınız yok mu?',
    'auth.haveAccount': 'Zaten hesabınız var mı?',
    'auth.registerLink': 'Kayıt olun',
    'auth.loginLink': 'Giriş yapın',
    'auth.wrongCredentials': 'E-posta veya şifre yanlış.',
    'account.user': 'Kullanıcı',
    'account.logout': 'Çıkış',
    'account.myReservations': 'Rezervasyonlarım',
    'account.profileInfo': 'Profil Bilgileri',
    'account.noReservation': 'Rezervasyon bulunamadı',
    'account.noReservationDesc': 'Henüz bir rezervasyonunuz yok.',
    'account.searchTour': 'Tur Ara',
    'account.personalInfo': 'Kişisel Bilgiler',
    'account.edit': 'Düzenle',
    'account.cancel': 'İptal',
    'account.save': 'Kaydet',
    'account.saving': 'Kaydediliyor...',
    'account.emailLabel': 'E-posta',
    'account.fullName': 'Ad Soyad',
    'account.enterName': 'Adınızı girin',
    'account.phone': 'Telefon',
    'account.birthDate': 'Doğum Tarihi',
    'account.passport': 'Pasaport Numarası',
    'account.notEntered': 'Girilmedi',
    'account.loading': 'Yükleniyor...',
    'account.tour': 'Tur',
    'account.hotel': 'Otel',
    'account.flight': 'Uçuş',
    'account.confirmed': 'Onaylandı',
    'account.pending': 'Beklemede',
    'account.cancelled': 'İptal Edildi',
    'account.persons': 'kişi',
    'account.orderedOn': 'tarihinde sipariş verildi',
    'checkout.title': 'Rezervasyon',
    'checkout.back': 'Geri',
    'checkout.flightSummary': 'Uçuş Özeti',
    'checkout.directFlight': 'Direkt Uçuş',
    'checkout.stops': 'Aktarma',
    'checkout.passengerInfo': 'Yolcu Bilgileri',
    'checkout.firstName': 'Ad',
    'checkout.firstNamePlaceholder': 'Adınız',
    'checkout.lastName': 'Soyad',
    'checkout.lastNamePlaceholder': 'Soyadınız',
    'checkout.email': 'E-posta',
    'checkout.phone': 'Telefon',
    'checkout.birthDate': 'Doğum Tarihi',
    'checkout.gender': 'Cinsiyet',
    'checkout.selectGender': 'Seçiniz',
    'checkout.male': 'Erkek',
    'checkout.female': 'Kadın',
    'checkout.nationality': 'Uyruk',
    'checkout.nationalityPlaceholder': 'Türkiye',
    'checkout.passportNo': 'Pasaport No',
    'checkout.emailPlaceholder': 'ornek@email.com',
    'checkout.priceSummary': 'Fiyat Özeti',
    'checkout.baseFare': 'Bilet Ücreti',
    'checkout.taxes': 'Vergiler',
    'checkout.serviceFee': 'Hizmet Bedeli',
    'checkout.total': 'Toplam',
    'checkout.payNow': 'Ödeme Yap',
    'checkout.processing': 'İşleniyor...',
    'checkout.securePayment': '256-bit SSL ile güvenli ödeme',
    'checkout.required': 'Bu alan zorunludur',
    'checkout.invalidEmail': 'Geçerli bir e-posta adresi giriniz',
    'checkout.noFlight': 'Uçuş Bulunamadı',
    'checkout.noFlightDesc': 'Lütfen uçuş aramaya geri dönün ve bir uçuş seçin.',
    'checkout.backToSearch': 'Aramaya Dön',
    'checkout.successTitle': 'Rezervasyonunuz Tamamlandı!',
    'checkout.successDesc': 'Biletiniz başarıyla oluşturuldu.',
    'checkout.reservationNo': 'Rezervasyon No',
    'checkout.route': 'Güzergah',
    'checkout.passenger': 'Yolcu',
    'checkout.emailSent': 'Bilet detayları e-posta adresinize gönderildi:',
    'checkout.backToHome': 'Ana Sayfaya Dön',
    'checkout.hotelSummary': 'Otel Bilgileri',
    'checkout.nights': 'gece',
    'checkout.guests': 'Misafirler',
    'checkout.guestInfo': 'Misafir Bilgileri',
    'checkout.guestN': 'Misafir',
    'checkout.noBooking': 'Rezervasyon Bulunamadı',
    'checkout.noBookingDesc': 'Lütfen geri dönün ve bir seçim yapın.',
    'checkout.hotelSuccessDesc': 'Otel rezervasyonunuz başarıyla oluşturuldu.',
    'checkout.hotel': 'Otel',
    'checkout.checkIn': 'Giriş',
    'checkout.checkOut': 'Çıkış',
    'filter.stops': 'Aktarmalar',
    'filter.allFlights': 'Tüm uçuşlar',
    'filter.oneStop': '1 Aktarma',
    'filter.directFlight': 'Direkt uçuş',
    'policy.legalDocuments': 'Hukuki Belgeler',
    'policy.legalDocumentsDesc': 'TourAgent Travel hizmetleri ile ilgili tüm hukuki şartlar ve kurallar',
    'policy.refundTitle': 'İade Politikası',
    'policy.refundIntro': 'Bu İade Politikası touragent.az web sitesi aracılığıyla sunulan tüm hizmetlere uygulanır.',
    'policy.refund1Title': '1. Uçak biletleri:',
    'policy.refund1Desc': 'Uçak biletlerinin iptal ve iade koşulları doğrudan ilgili havayolunun tarife kurallarına göre düzenlenir. İade edilemeyen tarifelerde ödemenin iadesi mümkün değildir.',
    'policy.refund2Title': '2. Otel rezervasyonları ve tur paketleri:',
    'policy.refund2Desc': 'Otel ve tur paketi rezervasyonlarının iade koşulları, ortak otel ve tur operatörlerinin iç kurallarına göre belirlenir.',
    'policy.refund3Title': '3. Vize hizmetleri:',
    'policy.refund3Desc': 'Vize harçları, konsolosluk ücretleri ve vize destek hizmetleri için ödenen tutarlar, başvuru sonucundan bağımsız olarak iade edilmez.',
    'policy.refund4Title': '4. Mücbir sebepler:',
    'policy.refund4Desc': 'Doğal afetler, havayollarının uçuşları iptal etmesi ve diğer mücbir sebep durumlarında iade, ortak şirketlerin kurallarına göre yapılır.',
    'policy.refund5Title': '5. İade süresi:',
    'policy.refund5Desc': 'Onaylanan iade tutarı, banka ve ödeme sistemlerinin iç kurallarına uygun olarak müşterinin hesabına aktarılır.',
    'policy.privacyTitle': 'Gizlilik Politikası',
    'policy.privacyIntro': 'TourAgent Travel, müşterilerin kişisel verilerinin korunmasını yürürlükteki mevzuata uygun şekilde sağlar.',
    'policy.privacy1Title': '1. Toplanan veriler:',
    'policy.privacy1Desc': 'Ad, soyad, iletişim numarası, e-posta adresi, kimlik bilgileri ve seyahat bilgileri yalnızca hizmetlerin ifası amacıyla toplanır.',
    'policy.privacy2Title': '2. Verilerin kullanımı:',
    'policy.privacy2Desc': 'Kişisel veriler yalnızca siparişlerin ifası, vize başvuruları, rezervasyon süreçleri ve müşteriyle iletişim için kullanılır.',
    'policy.privacy3Title': '3. Verilerin paylaşımı:',
    'policy.privacy3Desc': 'Veriler yalnızca hizmetin ifası için gerekli olan iş ortaklarına aktarılabilir ve üçüncü taraflara satılmaz.',
    'policy.privacy4Title': '4. Güvenlik:',
    'policy.privacy4Desc': 'Şirket, kişisel verilerin yetkisiz erişimden, değiştirilmeden ve yayılmadan korunması için teknik ve idari tedbirler alır.',
    'policy.privacy5Title': '5. Müşteri hakları:',
    'policy.privacy5Desc': 'Müşteri, kişisel verilerinin değiştirilmesi, silinmesi veya kullanımının kısıtlanması için istediği zaman başvurabilir.',
    'policy.termsTitle': 'Şartlar ve Koşullar',
    'policy.termsIntro': 'Bu Şartlar ve Koşullar, touragent.az web sitesini kullanan tüm kişiler için hukuken bağlayıcıdır.',
    'policy.terms1Title': '1. Genel hükümler:',
    'policy.terms1Desc': 'Siteyi kullanan kişi, bu şartları okuduğunu ve kabul ettiğini onaylamış sayılır.',
    'policy.terms2Title': '2. Sorumluluk:',
    'policy.terms2Desc': 'Müşteri, sunduğu bilgilerin doğruluğundan tam olarak sorumludur.',
    'policy.terms3Title': '3. Fiyat değişiklikleri:',
    'policy.terms3Desc': 'Fiyatlar, iş ortağı şirketlerin tarifelerine uygun olarak önceden bildirilmeksizin değiştirilebilir.',
    'policy.terms4Title': '4. Üçüncü taraflar:',
    'policy.terms4Desc': 'Havayolu, otel ve diğer iş ortaklarının sunduğu hizmetlerden TourAgent Travel sınırlı sorumluluk taşır.',
    'policy.terms5Title': '5. Değişiklik hakkı:',
    'policy.terms5Desc': 'Şirket, bu şart ve koşullarda istediği zaman değişiklik yapma hakkını saklı tutar.',
    'policy.terms6Title': '6. Uyuşmazlıklar:',
    'policy.terms6Desc': 'Ortaya çıkan uyuşmazlıklar yürürlükteki mevzuata uygun olarak çözümlenir.',
    'serviceDetail.notFound': 'Hizmet bulunamadı',
    'serviceDetail.backToServices': 'Hizmetlere dön',
    'serviceDetail.allServices': 'Tüm Hizmetler',
    'serviceDetail.aboutService': 'Hizmet Hakkında',
    'serviceDetail.interested': 'İlgileniyor musunuz?',
    'serviceDetail.contactForMore': 'Bu hizmet hakkında daha fazla bilgi almak için bizimle iletişime geçin.',
    'serviceDetail.callUs': 'Ara',
    'serviceDetail.hotelDetailed': 'Dünyanın her yerindeki otellerle işbirliği yaparak size en uygun fiyatlarla otel rezervasyonu hizmeti sunuyoruz. Lüks beş yıldızlı otellerden bütçeye uygun butik otellere kadar seçim sizin.',
    'serviceDetail.flightDetailed': 'Dünyanın önde gelen havayollarıyla doğrudan bağlantımız sayesinde size en uygun fiyatlarla uçak bileti sunuyoruz. Ekonomi, iş ve birinci sınıf biletler mevcuttur.',
    'serviceDetail.tourDetailed': 'Bireysel ve grup tur paketlerimizle unutulmaz seyahat deneyimleri yaşayın. Otel, transfer, gezi ve rehber hizmetlerini kapsayan tam paketler sunuyoruz.',
    'serviceDetail.honeymoonDetailed': 'Hayatınızın en özel anlarından birini gerçek bir mucizeye dönüştürün. Maldivler, Bali, Santorini, Paris ve daha birçok romantik destinasyona özel balayı paketlerimiz var.',
    'serviceDetail.medicalDetailed': 'Sağlığınıza yatırım yapın! Naftalan, Karlovy Vary, Gürcistan termal suları ve diğer ünlü tedavi merkezlerine turlar düzenliyoruz.',
    'serviceDetail.regionalDetailed': 'Azerbaycan\'ın zengin doğasını ve kültürel mirasını keşfedin! Şeki, Gabala, Lenkeran ve diğer güzel bölgelere turlar düzenliyoruz.',
    'serviceDetail.schoolDetailed': 'Çocuklarınız için güvenli, eğlenceli ve öğretici turlar düzenliyoruz. Yaz kampları, bilim turları ve doğa gezileri programımıza dahildir.',
    'serviceDetail.visaDetailed': 'Vize sürecinizi sizin için kolaylaştırıyoruz! ABD, Kanada, İngiltere, Schengen ülkeleri ve diğer destinasyonlara vize başvurularında tam destek sağlıyoruz.',
    'serviceDetail.transferDetailed': 'Havalimanından otelinize veya istediğiniz noktaya rahat ve güvenli transfer hizmeti sunuyoruz. Standart sedan, minivan, lüks araç ve VIP transfer seçeneklerimiz mevcuttur.',
    'serviceDetail.insuranceDetailed': 'Seyahat sigortası ile beklenmedik durumlara karşı kendinizi koruyun. Tıbbi harcamalar, bagaj kaybı, uçuş gecikmesi ve seyahat iptali risklerine karşı kapsamlı sigorta paketlerimiz mevcuttur.',
    'serviceDetail.bestPrice': 'En iyi fiyat garantisi',
    'serviceDetail.freeCancellation': 'Ücretsiz iptal imkanı',
    'serviceDetail.support247': '7/24 destek',
    'serviceDetail.fastOnlineBooking': 'Hızlı online rezervasyon',
    'serviceDetail.affordablePrices': 'Uygun fiyatlar',
    'serviceDetail.flexibleDates': 'Esnek tarih değişikliği',
    'serviceDetail.groupDiscounts': 'Grup indirimleri',
    'serviceDetail.extraBaggage': 'Ek bagaj desteği',
    'serviceDetail.fullPackage': 'Tam paket hizmet',
    'serviceDetail.individualGroup': 'Bireysel ve grup turları',
    'serviceDetail.proGuide': 'Profesyonel rehber',
    'serviceDetail.everyBudget': 'Her bütçeye uygun',
    'serviceDetail.romanticDecor': 'Romantik dekorasyon',
    'serviceDetail.luxuryRooms': 'Lüks odalar',
    'serviceDetail.spaServices': 'Spa hizmetleri',
    'serviceDetail.specialDinner': 'Özel akşam yemeği',
    'serviceDetail.doctorAdvice': 'Doktor tavsiyesi',
    'serviceDetail.modernTreatment': 'Modern tedavi',
    'serviceDetail.comfortConditions': 'Rahat koşullar',
    'serviceDetail.personalProgram': 'Kişisel program',
    'serviceDetail.comfortTransport': 'Konforlu ulaşım',
    'serviceDetail.localCuisine': 'Yerel mutfak',
    'serviceDetail.corporatePackages': 'Kurumsal paketler',
    'serviceDetail.safeEnvironment': 'Güvenli ortam',
    'serviceDetail.proSupervision': 'Profesyonel denetim',
    'serviceDetail.funProgram': 'Eğlenceli program',
    'serviceDetail.educationalContent': 'Eğitici içerik',
    'serviceDetail.docPreparation': 'Belge hazırlığı',
    'serviceDetail.interviewPrep': 'Mülakat hazırlığı',
    'serviceDetail.highApproval': 'Yüksek onay oranı',
    'serviceDetail.allCountries': 'Tüm ülkeler',
    'serviceDetail.vipTransfer': 'VIP transfer',
    'serviceDetail.proDriver': 'Profesyonel sürücü',
    'serviceDetail.groupTransfer': 'Grup transferi',
    'serviceDetail.service247': '7/24 hizmet',
    'serviceDetail.medicalInsurance': 'Sağlık sigortası',
    'serviceDetail.baggageInsurance': 'Bagaj sigortası',
    'serviceDetail.cancellationInsurance': 'İptal sigortası',
    'serviceDetail.visaInsurance': 'Vize sigortası',
  },
  en: {
    'header.services': 'Services',
    'header.help': 'Help',
    'header.account': 'My Account',
    'header.login': 'Login',
    'header.register': 'Sign Up',
    'header.contact': 'Contact',
    'header.customerService': '24/7 Customer Service',
    'header.whatsapp': 'WhatsApp',
    'header.instantSupport': 'Instant support',
    'header.aboutUs': 'About Us',
    'header.emailLabel': 'Email',
    'header.customerPanel': 'Customer Panel',
    'header.logout': 'Logout',
    'header.whereToGo': 'Where do you want to go?',
    'header.date': 'Date',
    'header.guest': 'Guest',
    'header.search': 'Search',
    'hero.title': "Azerbaijan's Travel Site",
    'hero.flight': 'Flight ticket',
    'hero.hotel': 'Hotel',
    'hero.tour': 'Tour',
    'hero.bus': 'Bus',
    'hero.carRental': 'Car rental',
    'hero.transfer': 'Transfer',
    'hero.oneWay': 'One way',
    'hero.roundTrip': 'Round trip',
    'hero.multiCity': 'Multi-city',
    'hero.nonStop': 'Non-stop',
    'hero.from': 'From',
    'hero.to': 'To',
    'hero.departDate': 'Departure Date',
    'hero.addReturn': 'Add Return',
    'hero.passengers': 'Passengers',
    'hero.passenger': 'Passenger',
    'hero.economy': 'Economy',
    'hero.findCheapTicket': 'Find cheap ticket',
    'hero.listHotels': 'Also list hotels for these dates',
    'hero.cabinEconomy': 'Economy',
    'hero.cabinPremium': 'Premium',
    'hero.cabinBusiness': 'Business',
    'hero.cabinFirst': 'First',
    'hero.departureCity': 'Departure City',
    'hero.selectCity': 'Select city',
    'hero.country': 'Country',
    'hero.selectCountry': 'Select country',
    'hero.airline': 'Airline',
    'hero.allAirlines': 'All',
    'hero.guests': 'Guests',
    'hero.guest': 'Guest',
    'hero.departureFrom': 'Departure From',
    'hero.departureTo': 'Departure To',
    'hero.nightsMin': 'Nights (Min)',
    'hero.nightsMax': 'Nights (Max)',
    'hero.night': 'night',
    'hero.searchTour': 'Search Tour',
    'hero.cheapest': 'Cheapest',
    'hero.fastest': 'Fastest',
    'hero.more': 'More',
    'hero.resultsFound': 'results found',
    'hero.closeResults': 'Close results',
    'hero.adult': 'Adult',
    'hero.child': 'Child',
    'hero.childAge': 'Child age',
    'hero.addChild': 'Add child',
    'hero.apply': 'Apply',
    'hero.flightDetails': 'Flight details',
    'hero.outbound': 'Outbound',
    'hero.return': 'Return',
    'hero.selectFlight': 'Select this flight',
    'hero.directFlight': 'Direct Flight',
    'hero.stopover': 'Stopover',
    'hero.sponsored': 'Sponsored',
    'hero.businessClass': 'Business Class',
    'datePicker.title': 'Check-in and Check-out Date',
    'datePicker.checkIn': 'Check-in Date',
    'datePicker.checkOut': 'Check-out Date',
    'datePicker.guests': 'Number of Guests',
    'datePicker.adults': 'Adults',
    'datePicker.room': 'Room',
    'datePicker.calendarSearch': 'Search Calendar',
    'datePicker.holidays': 'Public Holidays',
    'datePicker.apply': 'Apply',
    'datePicker.holidaysComingSoon': 'Public holidays coming soon...',
    'day.mon': 'Mon', 'day.tue': 'Tue', 'day.wed': 'Wed', 'day.thu': 'Thu', 'day.fri': 'Fri', 'day.sat': 'Sat', 'day.sun': 'Sun',
    'month.january': 'January', 'month.february': 'February', 'month.march': 'March', 'month.april': 'April', 'month.may': 'May', 'month.june': 'June', 'month.july': 'July', 'month.august': 'August', 'month.september': 'September', 'month.october': 'October', 'month.november': 'November', 'month.december': 'December',
    'deals.title': 'Flight deals',
    'deals.newYear': 'New Year Deals',
    'deals.international': 'International',
    'deals.domestic': 'Domestic',
    'deals.viewAll': 'View all',
    'destinations.title': 'Popular Destinations',
    'destinations.exploreAll': 'Explore All',
    'destinations.from': 'starting from',
    'destinations.subtitle': 'Discover the most popular destinations and collect unforgettable memories',
    'destinations.hotelOptions': 'hotel options',
    'destinations.lowest': 'From',
    'destinations.explore': 'Explore',
    'hotels.title': 'Featured Hotels',
    'hotels.viewAll': 'View All Hotels',
    'hotels.night': 'night',
    'hotels.from': 'starting from',
    'hotels.rating': 'Rating',
    'hotels.reviews': 'reviews',
    'hotels.bookNow': 'Book Now',
    'hotels.mostPopular': 'Most Popular',
    'hotels.new': 'New',
    'hotels.discount': 'Discount',
    'hotels.wifi': 'Wifi',
    'hotels.parking': 'Parking',
    'hotels.restaurant': 'Restaurant',
    'hotels.pool': 'Pool',
    'hotels.perNight': 'per night',
    'hotels.maxxRoyalDesc': 'Unforgettable vacation with luxury golf resort',
    'hotels.titanicDesc': 'Magnificent palace architecture and luxury service',
    'hotels.voyageDesc': 'Perfect combination of golf and spa',
    'hotels.delphinDesc': 'Family-friendly ultra all-inclusive resort',
    'campaigns.title': 'Special Campaigns',
    'campaigns.subtitle': 'Take advantage of limited-time special offers and grab your dream vacation at great prices',
    'campaigns.viewAll': 'View All',
    'campaigns.upTo': 'up to',
    'campaigns.discount': 'discount',
    'campaigns.details': 'View Details',
    'campaigns.explore': 'Explore',
    'campaigns.until': 'until',
    'campaigns.summer': 'Last Summer Deals',
    'campaigns.summerDesc': 'Vacation fun with 40% discount',
    'campaigns.earlyBird': 'Early Booking',
    'campaigns.earlyBirdDesc': 'Special prices for summer 2026',
    'campaigns.romantic': 'Romantic for Couples',
    'campaigns.romanticDesc': 'Big discount on honeymoon packages',
    'campaigns.limitedTime': 'Limited Time',
    'campaigns.specialPrice': 'Special Price',
    'campaigns.romanticBadge': 'Romantic',
    'campaigns.notifications': 'Campaign Notifications',
    'campaigns.notificationsDesc': 'Be the first to know about new deals',
    'campaigns.subscribe': 'Subscribe',
    'campaigns.august31': 'August 31',
    'campaigns.september15': 'September 15',
    'campaigns.september10': 'September 10',
    'earlyBooking.title': 'Early Booking Deals',
    'earlyBooking.saveUpTo': 'save up to',
    'earlyBooking.bookNow': 'Book Now',
    'earlyBooking.benefit1Title': 'Best Price Guarantee',
    'earlyBooking.benefit1Desc': 'Get the best prices with early booking',
    'earlyBooking.benefit2Title': 'Free Cancellation',
    'earlyBooking.benefit2Desc': 'Free cancellation up to 7 days before',
    'earlyBooking.benefit3Title': 'Secure Payment',
    'earlyBooking.benefit3Desc': 'Secure payment with 256-bit SSL encryption',
    'earlyBooking.benefit4Title': '24/7 Support',
    'earlyBooking.benefit4Desc': 'Our professional team is always by your side',
    'earlyBooking.heading1': 'Plan Your 2026 Summer',
    'earlyBooking.heading2': 'Now and Save!',
    'earlyBooking.description': 'By booking early, secure the best hotels and protect your budget. Take action now for the vacation of your dreams!',
    'earlyBooking.bookBtn': 'Book Early',
    'earlyBooking.campaignsBtn': 'View Campaigns',
    'earlyBooking.discountLabel': 'Early Booking Discount',
    'earlyBooking.happyCustomers': 'Happy Customers',
    'blog.title': 'Blog',
    'blog.readMore': 'Read More',
    'blog.allArticles': 'All Articles',
    'blog.subtitle': 'Guides, tips and discovery recommendations to enrich your vacation experience',
    'blog.post1Title': '10 Places You Must See in Antalya',
    'blog.post1Excerpt': 'Discover the historical and natural beauties you must visit during your holiday in Antalya, the pearl of the Mediterranean.',
    'blog.post1Category': 'Travel Guide',
    'blog.post2Title': 'Best Summer Getaways: Aegean Coast',
    'blog.post2Excerpt': 'Lose yourself in the azure waters of the Aegean Sea. The most beautiful bays, historical sites and culinary stops.',
    'blog.post2Category': 'Discover',
    'blog.post3Title': 'Budget-Friendly Vacation Tips',
    'blog.post3Excerpt': 'Maximum fun with minimum budget! Secrets to having unforgettable vacation experiences without breaking the bank.',
    'blog.post3Category': 'Tips',
    'blog.minutes': 'minutes',
    'reviews.title': 'Customer Reviews',
    'reviews.whatTheySay': 'What Our Customers Say',
    'reviews.weeksAgo': 'weeks ago',
    'reviews.happyReviews': 'Happy Customer Reviews',
    'reviews.satisfaction': 'Customer Satisfaction',
    'reviews.support': 'Customer Support',
    'reviews.bookings': 'Successful Bookings',
    'reviews.experience': 'Years of Experience',
    'reviews.review1': 'My Antalya vacation with TourAgent was amazing! The booking process was very easy, and the recommended hotel exceeded our expectations.',
    'reviews.review2': 'Every detail was perfect on our family trip to Bodrum. The kids had a great time, and we got to relax.',
    'reviews.review3': 'We were worried about planning our honeymoon, but the TourAgent team supported us throughout the entire process. We had a romantic and unforgettable vacation.',
    'footer.about': 'About',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.blog': 'Blog',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.termsOfService': 'Terms of Service',
    'footer.privacy': 'Privacy',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.contactUs': 'Contact Us',
    'footer.partnerships': 'Partnerships',
    'footer.affiliates': 'Affiliates',
    'footer.description': 'Azerbaijan\'s most trusted travel platform.',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.followUs': 'Follow Us',
    'footer.newsletter': 'Get Special Offers',
    'footer.newsletterDesc': 'Receive the best holiday deals in your inbox',
    'footer.emailPlaceholder': 'Enter your email address',
    'footer.companyDesc': 'For 15 years, we have been proud to offer you the best vacation experiences. Your dream vacation is just one click away.',
    'footer.quickLinks': 'Quick Links',
    'footer.hotels': 'Hotels',
    'footer.flightTickets': 'Flight Tickets',
    'footer.carRentalFooter': 'Car Rental',
    'footer.activities': 'Activities',
    'footer.tourPackages': 'Tour Packages',
    'footer.lastMinuteDeals': 'Last Minute Deals',
    'footer.popularDestinations': 'Popular Destinations',
    'footer.antalyaHotels': 'Antalya Hotels',
    'footer.istanbulHotels': 'Istanbul Hotels',
    'footer.bodrumHotels': 'Bodrum Hotels',
    'footer.cappadociaHotels': 'Cappadocia Hotels',
    'footer.cesmeHotels': 'Cesme Hotels',
    'footer.marmarisHotels': 'Marmaris Hotels',
    'footer.customerServiceFooter': '24/7 Customer Service',
    'footer.generalInfo': 'General Information',
    'footer.refundPolicy': 'Refund Policy',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsConditions': 'Terms & Conditions',
    'services.title': 'Our Services',
    'services.subtitle': 'We Provide You The Best Travel Experience',
    'services.whyChooseUs': 'Why Choose Us?',
    'services.ourServices': 'Our Comprehensive Services',
    'services.whyUs': 'Why TourAgent?',
    'services.viewDetails': 'View Details',
    'services.happyCustomers': 'Happy Customers',
    'services.serviceTypes': 'Service Types',
    'services.countries': 'Countries',
    'services.customerSupport': 'Customer Support',
    'services.comprehensiveRange': 'Our Comprehensive Service Range',
    'services.comprehensiveDesc': 'One-stop solutions for all your travel needs from A to Z',
    'services.whyChooseUsDesc': 'We make a difference with our customer satisfaction-focused approach',
    'services.securePayment': 'Secure Payment',
    'services.securePaymentDesc': 'Secure payment infrastructure with 256-bit SSL encryption',
    'services.bestPrice': 'Best Price',
    'services.bestPriceDesc': 'We offer the most suitable options with price comparison',
    'services.support247': '24/7 Support',
    'services.support247Desc': 'Our professional team is always by your side',
    'services.customers5000': '5000+ Customers',
    'services.customers5000Desc': 'Trust and customer satisfaction earned in a short time',
    'services.ctaTitle': 'Share Your Travel Plans With Us',
    'services.ctaDesc': 'Our professional team is here to create custom travel packages for you',
    'services.contactUs': 'Contact Us',
    'services.hotelBooking': 'Hotel Booking',
    'services.hotelBookingDesc': 'Reliable hotel booking for comfortable and relaxing stays anywhere in the world.',
    'services.flightTickets': 'Flight Tickets',
    'services.flightTicketsDesc': 'Flight ticket sales and flight support to any destination at affordable prices.',
    'services.tourPackages': 'Tour Packages',
    'services.tourPackagesDesc': 'Organization of various individual and group tour packages for domestic and international destinations.',
    'services.honeymoon': 'Honeymoon Trips',
    'services.honeymoonDesc': 'Make your love even more unforgettable with special honeymoon programs.',
    'services.medicalTours': 'Medical Tours',
    'services.medicalToursDesc': 'Treatment and rest tours in selected sanatoriums for your health.',
    'services.regionalTours': 'Regional Tours',
    'services.regionalToursDesc': 'Comfortable and fun tours to the most beautiful regions of Azerbaijan.',
    'services.schoolTours': 'School Tours',
    'services.schoolToursDesc': 'Useful and interesting rest programs for students during school breaks.',
    'services.visaSupport': 'Visa Support',
    'services.visaSupportDesc': 'Full support for visa applications and documentation to many countries.',
    'services.transferService': 'Transfer Service',
    'services.transferServiceDesc': 'Standard and VIP transfer services in the country you are traveling to.',
    'services.insurance': 'Insurance',
    'services.insuranceDesc': 'Insurance services to guarantee your safety throughout your journey.',
    'about.since': 'since',
    'about.title': 'About Us',
    'about.subtitle': 'TourAgent Travel – trust your journey to the real expert!',
    'about.happyCustomers': 'Happy Customers',
    'about.foundedYear': 'Founded',
    'about.customerSupport': 'Customer Support',
    'about.countries': 'Countries',
    'about.professionalTourism': 'Professional Tourism',
    'about.servicesLabel': 'Services',
    'about.mainDesc1': 'TourAgent Travel is a professional tourism company founded in 2022 that has provided quality travel services to over 5,000 customers in a short period.',
    'about.mainDesc2': 'Our main goal is to offer the most suitable solution for every customer\'s budget, preferred date, and travel needs.',
    'about.affordableFlights': 'Affordable Flights',
    'about.hotelBooking': 'Hotel Booking',
    'about.tourPackagesLabel': 'Tour Packages',
    'about.visaSupportLabel': 'Visa Support',
    'about.servicesDetail': 'Detailed Service Information',
    'about.servicesDetailDesc': 'We offer a wide range of services to provide you with the best travel experience',
    'about.flightService': 'Flight Ticket Service',
    'about.flightServiceDesc': 'We find the most suitable flight tickets in any direction quickly and provide all flight information in detail before the flight.',
    'about.tourOrganization': 'Tour Package Organization',
    'about.tourOrganizationDesc': 'We organize domestic and international tours, individual, group and family tours, youth tours, medical tours, honeymoon tours and special occasion tours.',
    'about.internationalTours': 'International Tour Packages',
    'about.internationalToursDesc': 'In international tour packages, we offer hotel options from 3-star to 5-star to ensure our customers\' comfortable vacation.',
    'about.specialTours': 'Special Tours',
    'about.specialToursDesc': 'We offer sanatorium programs for customers with health issues, honeymoon tours for newlyweds, and special New Year\'s programs.',
    'about.transferVip': 'Transfer and VIP Services',
    'about.transferVipDesc': 'Standard and VIP transfer services are available. We ensure your safe transportation from the airport to your hotel.',
    'about.visaService': 'Visa Support',
    'about.visaServiceDesc': 'We provide full support for obtaining your visa when you are eligible. We are with you from document preparation to application tracking.',
    'about.alwaysWithYou': 'We are with you throughout all our services',
    'about.alwaysWithYouDesc': 'We maintain constant communication with our customers throughout all our services and are at your service 24/7.',
    'about.fastResponse': 'Fast Response',
    'about.inMinutes': 'Within 5 minutes',
    'about.secure': 'Secure',
    'about.sslEncryption': 'SSL encryption',
    'about.international': 'International',
    'about.countriesPlus': '50+ countries',
    'about.proTeam': 'Professional Team',
    'about.experiencedStaff': 'Experienced staff',
    'about.shareYourPlans': 'Share your travel plans with us',
    'about.betterTravel': 'Travel better and hassle-free.',
    'about.trustAgent': 'TourAgent Travel – trust your journey to the real expert!',
    'about.contactInfo': 'Contact Information',
    'about.contactAnytime': 'You can contact us at any time',
    'about.address': 'Address',
    'about.email': 'Email',
    'about.phone': 'Phone',
    'about.whatsappLines': 'Our WhatsApp Lines',
    'about.writeOnWhatsapp': 'Write on WhatsApp',
    'auth.memberLogin': 'Member Login',
    'auth.registration': 'Registration',
    'auth.loginToAccount': 'Login to your account',
    'auth.createAccount': 'Create a new account',
    'auth.login': 'Login',
    'auth.register': 'Sign Up',
    'auth.fullName': 'Full Name',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.loginBtn': 'Login',
    'auth.registerBtn': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.registerLink': 'Sign up',
    'auth.loginLink': 'Login',
    'auth.wrongCredentials': 'Email or password is incorrect.',
    'account.user': 'User',
    'account.logout': 'Logout',
    'account.myReservations': 'My Reservations',
    'account.profileInfo': 'Profile Information',
    'account.noReservation': 'No reservations found',
    'account.noReservationDesc': 'You don\'t have any reservations yet.',
    'account.searchTour': 'Search Tour',
    'account.personalInfo': 'Personal Information',
    'account.edit': 'Edit',
    'account.cancel': 'Cancel',
    'account.save': 'Save',
    'account.saving': 'Saving...',
    'account.emailLabel': 'Email',
    'account.fullName': 'Full Name',
    'account.enterName': 'Enter your name',
    'account.phone': 'Phone',
    'account.birthDate': 'Date of Birth',
    'account.passport': 'Passport Number',
    'account.notEntered': 'Not entered',
    'account.loading': 'Loading...',
    'account.tour': 'Tour',
    'account.hotel': 'Hotel',
    'account.flight': 'Flight',
    'account.confirmed': 'Confirmed',
    'account.pending': 'Pending',
    'account.cancelled': 'Cancelled',
    'account.persons': 'persons',
    'account.orderedOn': 'ordered on',
    'checkout.title': 'Booking',
    'checkout.back': 'Back',
    'checkout.flightSummary': 'Flight Summary',
    'checkout.directFlight': 'Direct Flight',
    'checkout.stops': 'Stops',
    'checkout.passengerInfo': 'Passenger Information',
    'checkout.firstName': 'First Name',
    'checkout.firstNamePlaceholder': 'Your first name',
    'checkout.lastName': 'Last Name',
    'checkout.lastNamePlaceholder': 'Your last name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone',
    'checkout.birthDate': 'Date of Birth',
    'checkout.gender': 'Gender',
    'checkout.selectGender': 'Select',
    'checkout.male': 'Male',
    'checkout.female': 'Female',
    'checkout.nationality': 'Nationality',
    'checkout.nationalityPlaceholder': 'Azerbaijan',
    'checkout.passportNo': 'Passport No',
    'checkout.emailPlaceholder': 'example@email.com',
    'checkout.priceSummary': 'Price Summary',
    'checkout.baseFare': 'Base Fare',
    'checkout.taxes': 'Taxes',
    'checkout.serviceFee': 'Service Fee',
    'checkout.total': 'Total',
    'checkout.payNow': 'Pay Now',
    'checkout.processing': 'Processing...',
    'checkout.securePayment': 'Secure payment with 256-bit SSL',
    'checkout.required': 'This field is required',
    'checkout.invalidEmail': 'Please enter a valid email address',
    'checkout.noFlight': 'Flight Not Found',
    'checkout.noFlightDesc': 'Please go back to flight search and select a flight.',
    'checkout.backToSearch': 'Back to Search',
    'checkout.successTitle': 'Booking Completed!',
    'checkout.successDesc': 'Your ticket has been successfully created.',
    'checkout.reservationNo': 'Reservation No',
    'checkout.route': 'Route',
    'checkout.passenger': 'Passenger',
    'checkout.emailSent': 'Ticket details have been sent to:',
    'checkout.backToHome': 'Back to Home',
    'checkout.hotelSummary': 'Hotel Details',
    'checkout.nights': 'nights',
    'checkout.guests': 'Guests',
    'checkout.guestInfo': 'Guest Information',
    'checkout.guestN': 'Guest',
    'checkout.noBooking': 'Booking Not Found',
    'checkout.noBookingDesc': 'Please go back and make a selection.',
    'checkout.hotelSuccessDesc': 'Your hotel reservation has been successfully created.',
    'checkout.hotel': 'Hotel',
    'checkout.checkIn': 'Check-in',
    'checkout.checkOut': 'Check-out',
    'filter.stops': 'Stops',
    'filter.allFlights': 'All flights',
    'filter.oneStop': '1 Stop',
    'filter.directFlight': 'Direct flight',
  },
  az: {
    'header.services': 'Xidmətlər',
    'header.help': 'Kömək',
    'header.account': 'Hesabım',
    'header.login': 'Daxil ol',
    'header.register': 'Qeydiyyat',
    'header.contact': 'Əlaqə',
    'header.customerService': '7/24 Müştəri Xidmətləri',
    'header.whatsapp': 'WhatsApp',
    'header.instantSupport': 'Ani dəstək',
    'header.aboutUs': 'Haqqımızda',
    'header.emailLabel': 'E-poçt',
    'header.customerPanel': 'Müştəri Paneli',
    'header.logout': 'Çıxış',
    'header.whereToGo': 'Hara getmək istəyirsiniz?',
    'header.date': 'Tarix',
    'header.guest': 'Qonaq',
    'header.search': 'Axtar',
    'hero.title': 'Azərbaycanın Səyahət Saytı',
    'hero.flight': 'Təyyarə bileti',
    'hero.hotel': 'Otel',
    'hero.tour': 'Tur',
    'hero.bus': 'Avtobus',
    'hero.carRental': 'Maşın icarəsi',
    'hero.transfer': 'Transfer',
    'hero.oneWay': 'Tək istiqamət',
    'hero.roundTrip': 'Getmə-gəlmə',
    'hero.multiCity': 'Çoxlu uçuş',
    'hero.nonStop': 'Dayanacaqsız',
    'hero.from': 'Haradan',
    'hero.to': 'Hara',
    'hero.departDate': 'Getmə Tarixi',
    'hero.addReturn': 'Qayıdış əlavə et',
    'hero.passengers': 'Sərnişin',
    'hero.passenger': 'Sərnişin',
    'hero.economy': 'Ekonom',
    'hero.findCheapTicket': 'Ucuz bilet tap',
    'hero.listHotels': 'Bu tarixlər üçün otelləri də siyahıya sal',
    'hero.cabinEconomy': 'Ekonom',
    'hero.cabinPremium': 'Premium',
    'hero.cabinBusiness': 'Biznes',
    'hero.cabinFirst': 'Birinci',
    'hero.departureCity': 'Çıxış Şəhəri',
    'hero.selectCity': 'Şəhər seçin',
    'hero.country': 'Ölkə',
    'hero.selectCountry': 'Ölkə seçin',
    'hero.airline': 'Aviaşirkət',
    'hero.allAirlines': 'Hamısı',
    'hero.guests': 'Qonaqlar',
    'hero.guest': 'Qonaq',
    'hero.departureFrom': 'Gediş',
    'hero.departureTo': 'Gediş Son',
    'hero.nightsMin': 'Gecə (Min)',
    'hero.nightsMax': 'Gecə (Maks)',
    'hero.night': 'gecə',
    'hero.searchTour': 'Tur Axtar',
    'hero.cheapest': 'Ən Ucuz',
    'hero.fastest': 'Ən Sürətli',
    'hero.more': 'Daha çox',
    'hero.resultsFound': 'nəticə tapıldı',
    'hero.closeResults': 'Nəticələri bağla',
    'hero.adult': 'Böyük',
    'hero.child': 'Uşaq',
    'hero.childAge': 'Uşaq yaşı',
    'hero.addChild': 'Uşaq əlavə et',
    'hero.apply': 'Tətbiq et',
    'hero.flightDetails': 'Uçuş detalları',
    'hero.outbound': 'Gediş',
    'hero.return': 'Qayıdış',
    'hero.selectFlight': 'Bu uçuşu seç',
    'hero.directFlight': 'Birbaşa Uçuş',
    'hero.stopover': 'Ötürmə',
    'hero.sponsored': 'Sponsorlu',
    'hero.businessClass': 'Biznes Klass',
    'datePicker.title': 'Giriş və Çıxış Tarixi',
    'datePicker.checkIn': 'Giriş Tarixi',
    'datePicker.checkOut': 'Çıxış Tarixi',
    'datePicker.guests': 'Qonaq Sayı',
    'datePicker.adults': 'Böyük',
    'datePicker.room': 'Otaq',
    'datePicker.calendarSearch': 'Təqvimdə Axtar',
    'datePicker.holidays': 'Rəsmi Bayramlar',
    'datePicker.apply': 'Tətbiq et',
    'datePicker.holidaysComingSoon': 'Rəsmi bayram günləri tezliklə əlavə olunacaq...',
    'day.mon': 'Bz', 'day.tue': 'Çax', 'day.wed': 'Çər', 'day.thu': 'Ca', 'day.fri': 'Cü', 'day.sat': 'Şə', 'day.sun': 'Ba',
    'month.january': 'Yanvar', 'month.february': 'Fevral', 'month.march': 'Mart', 'month.april': 'Aprel', 'month.may': 'May', 'month.june': 'İyun', 'month.july': 'İyul', 'month.august': 'Avqust', 'month.september': 'Sentyabr', 'month.october': 'Oktyabr', 'month.november': 'Noyabr', 'month.december': 'Dekabr',
    'deals.title': 'Endirimlə uçuşlar',
    'deals.newYear': 'Yeni İl Endirmləri',
    'deals.international': 'Beynəlxalq',
    'deals.domestic': 'Daxili',
    'deals.viewAll': 'Hamısını gör',
    'destinations.title': 'Populyar İstiqamətlər',
    'destinations.exploreAll': 'Hamısını Kəşf Et',
    'destinations.from': 'dan başlayan qiymətlərlə',
    'destinations.subtitle': 'Ən çox seçilən istiqamətləri kəşf edin və unudulmaz xatirələr yığın',
    'destinations.hotelOptions': 'otel seçimi',
    'destinations.lowest': 'Ən aşağı',
    'destinations.explore': 'Kəşf et',
    'hotels.title': 'Seçilmiş Otellər',
    'hotels.viewAll': 'Bütün Otelləri Gör',
    'hotels.night': 'gecə',
    'hotels.from': 'dan başlayan qiymətlərlə',
    'hotels.rating': 'Reytinq',
    'hotels.reviews': 'rəy',
    'hotels.bookNow': 'İndi Rezervasiya Et',
    'hotels.mostPopular': 'Ən Populyar',
    'hotels.new': 'Yeni',
    'hotels.discount': 'Endirim',
    'hotels.wifi': 'Wifi',
    'hotels.parking': 'Parkinq',
    'hotels.restaurant': 'Restoran',
    'hotels.pool': 'Hovuz',
    'hotels.perNight': 'gecəlik',
    'hotels.maxxRoyalDesc': 'Lüks qolf resort ilə unudulmaz tətil təcrübəsi',
    'hotels.titanicDesc': 'Möhtəşəm saray memarlığı və lüks xidmət',
    'hotels.voyageDesc': 'Qolf və spa-nın mükəmməl birləşməsi',
    'hotels.delphinDesc': 'Ailə dostu ultra hər şey daxil resort',
    'campaigns.title': 'Xüsusi Kampaniyalar',
    'campaigns.subtitle': 'Məhdud müddətli xüsusi təkliflərdən yararlanın',
    'campaigns.viewAll': 'Hamısını Gör',
    'campaigns.upTo': 'ə qədər',
    'campaigns.discount': 'endirim',
    'campaigns.details': 'Ətraflı Məlumat',
    'campaigns.explore': 'Kəşf Et',
    'campaigns.until': 'tarixinə qədər',
    'campaigns.summer': 'Yayın Son Fürsətləri',
    'campaigns.summerDesc': '%40 endirimlə tətil keyfi',
    'campaigns.earlyBird': 'Erkən Rezervasiya',
    'campaigns.earlyBirdDesc': '2026 yayı üçün xüsusi qiymətlər',
    'campaigns.romantic': 'Cütlər Üçün Romantik',
    'campaigns.romanticDesc': 'Balayı paketlərində böyük endirim',
    'campaigns.limitedTime': 'Məhdud Müddət',
    'campaigns.specialPrice': 'Xüsusi Qiymət',
    'campaigns.romanticBadge': 'Romantik',
    'campaigns.notifications': 'Xüsusi Kampaniya Bildirişləri',
    'campaigns.notificationsDesc': 'Yeni fürsətlərdən ilk sən xəbərdar ol',
    'campaigns.subscribe': 'Abunə Ol',
    'campaigns.august31': '31 Avqust',
    'campaigns.september15': '15 Sentyabr',
    'campaigns.september10': '10 Sentyabr',
    'earlyBooking.title': 'Erkən Rezervasiya Fürsətləri',
    'earlyBooking.saveUpTo': 'ə qədər qənaət',
    'earlyBooking.bookNow': 'İndi Rezerv Et',
    'earlyBooking.benefit1Title': 'Ən Yaxşı Qiymət Zəmanəti',
    'earlyBooking.benefit1Desc': 'Erkən rezervasiya ilə ən uyğun qiymətləri əldə edin',
    'earlyBooking.benefit2Title': 'Pulsuz Ləğv',
    'earlyBooking.benefit2Desc': '7 gün əvvəlinə qədər pulsuz ləğv hüququ',
    'earlyBooking.benefit3Title': 'Təhlükəsiz Ödəniş',
    'earlyBooking.benefit3Desc': '256-bit SSL şifrələmə ilə təhlükəsiz ödəniş',
    'earlyBooking.benefit4Title': '7/24 Dəstək',
    'earlyBooking.benefit4Desc': 'Peşəkar komandamız həmişə yanınızdadır',
    'earlyBooking.heading1': '2026 Yayını İndidən',
    'earlyBooking.heading2': 'Planla və Qazan!',
    'earlyBooking.description': 'Erkən rezervasiya edərək həm ən yaxşı otelləri zəmanət altına alın, həm də büdcənizi qoruyun. Xəyalınızdakı tətil üçün indi hərəkətə keçin!',
    'earlyBooking.bookBtn': 'Erkən Rezervasiya Et',
    'earlyBooking.campaignsBtn': 'Kampaniyalara Bax',
    'earlyBooking.discountLabel': 'Erkən Rezervasiya Endirimi',
    'earlyBooking.happyCustomers': 'Məmnun Müştəri',
    'blog.title': 'Bloq',
    'blog.readMore': 'Daha Çox Oxu',
    'blog.allArticles': 'Bütün Məqalələr',
    'blog.subtitle': 'Tətil təcrübənizi zənginləşdirən bələdçilər, ipucları və kəşf tövsiyələri',
    'blog.post1Title': 'Antalyada Görməli Olduğunuz 10 Yer',
    'blog.post1Excerpt': 'Aralıq dənizinin incisi Antalyada tətilinizdə mütləq ziyarət etməli olduğunuz tarixi və təbii gözəllikləri kəşf edin.',
    'blog.post1Category': 'Tətil Bələdçisi',
    'blog.post2Title': 'Yayın Ən Gözəl Qaçış Yerləri: Egey Sahilləri',
    'blog.post2Excerpt': 'Egey dənizinin masmavi sularında özünüzü itirin. Ən gözəl körfəzlər, tarixi məkanlar və ləzzət duracaqları.',
    'blog.post2Category': 'Kəşf',
    'blog.post3Title': 'Büdcəyə Uyğun Tətil Tövsiyələri',
    'blog.post3Excerpt': 'Az büdcə ilə çox keyf! Cibinizi yandırmadan unudulmaz tətil təcrübələri yaşamağın sirləri.',
    'blog.post3Category': 'İpucları',
    'blog.minutes': 'dəqiqə',
    'reviews.title': 'Müştəri Rəyləri',
    'reviews.whatTheySay': 'Müştərilərimiz Nə Deyir',
    'reviews.weeksAgo': 'həftə əvvəl',
    'reviews.happyReviews': 'Məmnun Müştəri Rəyi',
    'reviews.satisfaction': 'Müştəri Məmnuniyyəti',
    'reviews.support': 'Müştəri Dəstəyi',
    'reviews.bookings': 'Uğurlu Rezervasiya',
    'reviews.experience': 'İllik Təcrübə',
    'reviews.review1': 'TourAgent ilə etdiyim Antalya tətili əla idi! Həm rezervasiya prosesi çox asan oldu, həm də tövsiyə olunan otel gözləntilərimizi aşdı.',
    'reviews.review2': 'Ailəliklə getdiyimiz Bodrum tətilində hər detal mükəmməl idi. Uşaqlar çox əyləndi, biz də dincəldik.',
    'reviews.review3': 'Bal ayımızı planlaşdırarkən çox narahat idik, amma TourAgent komandası bütün prosesdə bizə dəstək oldu. Romantik və unudulmaz bir tətil keçirdik.',
    'footer.about': 'Haqqımızda',
    'footer.aboutUs': 'Haqqımızda',
    'footer.careers': 'Karyera',
    'footer.press': 'Mətbuat',
    'footer.blog': 'Bloq',
    'footer.support': 'Dəstək',
    'footer.helpCenter': 'Yardım Mərkəzi',
    'footer.termsOfService': 'Xidmət Şərtləri',
    'footer.privacy': 'Məxfilik',
    'footer.legal': 'Hüquqi',
    'footer.contact': 'Əlaqə',
    'footer.contactUs': 'Bizimlə Əlaqə',
    'footer.partnerships': 'İş Ortaqlıqları',
    'footer.affiliates': 'Tərəfdaşlar',
    'footer.description': 'Azərbaycanın ən etibarlı səyahət platforması.',
    'footer.allRightsReserved': 'Bütün hüquqlar qorunur.',
    'footer.followUs': 'Bizi İzləyin',
    'footer.newsletter': 'Xüsusi Təkliflərdən Xəbərdar Olun',
    'footer.newsletterDesc': 'Ən yaxşı tətil təklifləri və kampaniyaları e-poçt qutunuza gəlsin',
    'footer.emailPlaceholder': 'E-poçt ünvanınızı daxil edin',
    'footer.companyDesc': '15 ildir sizə ən gözəl tətil təcrübələrini sunmaqdan qürur duyuruq. Xəyalınızdakı tətil sadəcə bir klik uzağınızdadır.',
    'footer.quickLinks': 'Sürətli Bağlantılar',
    'footer.hotels': 'Otellər',
    'footer.flightTickets': 'Təyyarə Bileti',
    'footer.carRentalFooter': 'Maşın İcarəsi',
    'footer.activities': 'Aktivitələr',
    'footer.tourPackages': 'Tur Paketləri',
    'footer.lastMinuteDeals': 'Son Dəqiqə Fürsətləri',
    'footer.popularDestinations': 'Populyar İstiqamətlər',
    'footer.antalyaHotels': 'Antalya Otelləri',
    'footer.istanbulHotels': 'İstanbul Otelləri',
    'footer.bodrumHotels': 'Bodrum Otelləri',
    'footer.cappadociaHotels': 'Kapadokya Otelləri',
    'footer.cesmeHotels': 'Çeşme Otelləri',
    'footer.marmarisHotels': 'Marmaris Otelləri',
    'footer.customerServiceFooter': '7/24 Müştəri Xidmətləri',
    'footer.generalInfo': 'Ümumi Məlumat',
    'footer.refundPolicy': 'Geri Qaytarma Siyasəti',
    'footer.privacyPolicy': 'Məxfilik Siyasəti',
    'footer.termsConditions': 'Şərtlər və Qaydalar',
    'services.title': 'Xidmətlərimiz',
    'services.subtitle': 'Sizə Ən Yaxşı Səyahət Təcrübəsini Təqdim Edirik',
    'services.whyChooseUs': 'Niyə Bizi Seçməlisiniz?',
    'services.ourServices': 'Əhatəli Xidmət Çeşidimiz',
    'services.whyUs': 'Niyə TourAgent?',
    'services.viewDetails': 'Ətraflı Bax',
    'services.happyCustomers': 'Mutlu Müştəri',
    'services.serviceTypes': 'Xidmət Növü',
    'services.countries': 'Ölkə',
    'services.customerSupport': 'Müştəri Dəstəyi',
    'services.comprehensiveRange': 'Kapsamlı Xidmət Çeşidimiz',
    'services.comprehensiveDesc': 'A-dan Z-yə səyahət ehtiyaclarınız üçün tək durak həllər',
    'services.whyChooseUsDesc': 'Müştəri məmnuniyyəti odaqlı yanaşmamızla fərq yaradırıq',
    'services.securePayment': 'Təhlükəsiz Ödəniş',
    'services.securePaymentDesc': '256-bit SSL şifrələmə ilə təhlükəsiz ödəniş altyapısı',
    'services.bestPrice': 'Ən Yaxşı Qiymət',
    'services.bestPriceDesc': 'Qiymət müqayisəsi ilə ən uyğun seçimləri təklif edirik',
    'services.support247': '7/24 Dəstək',
    'services.support247Desc': 'Peşəkar komandamız həmişə yanınızdadır',
    'services.customers5000': '5000+ Müştəri',
    'services.customers5000Desc': 'Qısa müddətdə qazanılmış etibar və müştəri məmnuniyyəti',
    'services.ctaTitle': 'Səyahət Planlarınızı Bizimlə Bölüşün',
    'services.ctaDesc': 'Peşəkar komandamız sizə özel səyahət paketləri hazırlamaq üçün buradadır',
    'services.contactUs': 'Bizimlə Əlaqə',
    'services.hotelBooking': 'Otel Bronu',
    'services.hotelBookingDesc': 'Dünyanın istənilən nöqtəsində rahat və komfortlu istirahət üçün etibarlı otel bronu.',
    'services.flightTickets': 'Aviabiletlər',
    'services.flightTicketsDesc': 'Münasib qiymətlərlə istənilən istiqamətə aviabilet satışı və uçuş dəstəyi.',
    'services.tourPackages': 'Turpaketlər',
    'services.tourPackagesDesc': 'Daxili və xarici istiqamətlər üzrə müxtəlif növ fərdi və qrup turpaketlərinin təşkili.',
    'services.honeymoon': 'Balayı Səyahətləri',
    'services.honeymoonDesc': 'Xüsusi bal ayı proqramları ilə sevginizi daha da unudulmaz edin.',
    'services.medicalTours': 'Müalicəvi Turlar',
    'services.medicalToursDesc': 'Sağlamlığınız üçün seçilmiş sanatoriyalarda müalicə və istirahət turları.',
    'services.regionalTours': 'Rayon Turları',
    'services.regionalToursDesc': 'Azərbaycanın ən gözəl bölgələrinə komfortlu və əyləncəli turlar.',
    'services.schoolTours': 'Məktəbli Turları',
    'services.schoolToursDesc': 'Təhsil arası faydalı və maraqlı istirahət proqramları məktəblilər üçün.',
    'services.visaSupport': 'Viza Dəstəyi',
    'services.visaSupportDesc': 'Bir çox ölkələrə viza müraciəti və sənədləşmə üzrə tam dəstək.',
    'services.transferService': 'Transfer Xidməti',
    'services.transferServiceDesc': 'Səyahət etdiyiniz ölkədə standart və VİP transfer xidmətləri.',
    'services.insurance': 'Sığorta',
    'services.insuranceDesc': 'Səyahətiniz boyunca təhlükəsizliyinizin təminatı üçün sığorta xidmətləri.',
    'about.since': '-ci ildən bəri',
    'about.title': 'Haqqımızda',
    'about.subtitle': 'TourAgent Travel – səyahətinizi əsl agentə etibar edin!',
    'about.happyCustomers': 'Mutlu Müştəri',
    'about.foundedYear': 'Təsis ili',
    'about.customerSupport': 'Müştəri Dəstəyi',
    'about.countries': 'Ölkə',
    'about.professionalTourism': 'Peşəkar Turizm',
    'about.servicesLabel': 'Xidmətlərimiz',
    'about.mainDesc1': 'TourAgent Travel 2022-ci ildə təsis olunmuş və qısa müddət ərzində 5000-dən çox müştəriyə keyfiyyətli səyahət xidmətləri göstərmiş peşəkar turizm şirkətidir.',
    'about.mainDesc2': 'Bizim əsas məqsədimiz hər bir müştərinin büdcəsinə, seçdiyi tarixə və səyahət tələblərinə uyğun ən doğru həlli təklif etməkdir.',
    'about.affordableFlights': 'Sərfəli Aviabilet',
    'about.hotelBooking': 'Otel Bronu',
    'about.tourPackagesLabel': 'Turpaketlər',
    'about.visaSupportLabel': 'Viza Dəstəyi',
    'about.servicesDetail': 'Xidmətlərimiz Haqqında Ətraflı',
    'about.servicesDetailDesc': 'Sizə ən yaxşı səyahət təcrübəsini təqdim etmək üçün geniş xidmət çeşidi təklif edirik',
    'about.flightService': 'Aviabilet Xidməti',
    'about.flightServiceDesc': 'İstənilən istiqamət üzrə ən münasib aviabiletləri qısa zamanda tapır, uçuşdan öncə bütün uçuş məlumatlarını ətraflı şəkildə təqdim edirik.',
    'about.tourOrganization': 'Turpaketlərin Təşkili',
    'about.tourOrganizationDesc': 'Daxili və xarici turlar, fərdi, qrup və ailə turları, gənclər üçün turlar, müalicəvi turlar, bal ayı turları və bayramlara özəl turpaketlər təşkil edirik.',
    'about.internationalTours': 'Xarici Turpaketlər',
    'about.internationalToursDesc': 'Xarici turpaketlərdə istər 3 ulduzlu, istərsə də 5 ulduzlu otellər seçilərək müştərilərin rahat istirahəti təmin olunur.',
    'about.specialTours': 'Xüsusi Turlar',
    'about.specialToursDesc': 'Sağlamlıq problemi olan müştərilər üçün sanatoriyalarda müalicə proqramları, yeni ailə quran cütlüklər üçün bal ayı turları və xüsusi proqramlar təqdim edirik.',
    'about.transferVip': 'Transfer və VİP Xidmətlər',
    'about.transferVipDesc': 'Standart və VİP transfer xidmətlərimiz mövcuddur. Havalimanından otelinizə təhlükəsiz nəqliyyatla çatdırılmanızı təmin edirik.',
    'about.visaService': 'Viza Dəstəyi',
    'about.visaServiceDesc': 'Tələblərə uyğun olduğunuz halda viza əldə etməyiniz üçün tam dəstək göstəririk. Sənədlərin hazırlanmasından müraciətin izlənməsinə qədər yanınızdayıq.',
    'about.alwaysWithYou': 'Bütün xidmətlərimiz boyunca yanınızdayıq',
    'about.alwaysWithYouDesc': 'Bütün xidmətlərimiz boyunca müştərilərimizlə daimi əlaqədə olur və 7/24 xidmətinizdəyik.',
    'about.fastResponse': 'Sürətli Cavab',
    'about.inMinutes': '5 dəqiqə ərzində',
    'about.secure': 'Təhlükəsiz',
    'about.sslEncryption': 'SSL şifrələmə',
    'about.international': 'Beynəlxalq',
    'about.countriesPlus': '50+ ölkə',
    'about.proTeam': 'Peşəkar Komanda',
    'about.experiencedStaff': 'Təcrübəli heyət',
    'about.shareYourPlans': 'Səyahət planlarınızı bizimlə bölüşün',
    'about.betterTravel': 'Daha keyfiyyətli və problemsiz səyahət edin.',
    'about.trustAgent': 'TourAgent Travel – səyahətinizi əsl agentə etibar edin!',
    'about.contactInfo': 'Əlaqə Məlumatları',
    'about.contactAnytime': 'Bizimlə istənilən vaxt əlaqə saxlaya bilərsiniz',
    'about.address': 'Ünvan',
    'about.email': 'E-poçt',
    'about.phone': 'Telefon',
    'about.whatsappLines': 'WhatsApp Xətlərimiz',
    'about.writeOnWhatsapp': 'WhatsApp ilə Yazın',
    'auth.memberLogin': 'Üzv Girişi',
    'auth.registration': 'Qeydiyyat',
    'auth.loginToAccount': 'Hesabınıza daxil olun',
    'auth.createAccount': 'Yeni hesab yaradın',
    'auth.login': 'Daxil ol',
    'auth.register': 'Qeydiyyat',
    'auth.fullName': 'Ad Soyad',
    'auth.emailAddress': 'E-poçt Ünvanı',
    'auth.password': 'Şifrə',
    'auth.forgotPassword': 'Şifrənizi unutmusunuz?',
    'auth.loginBtn': 'Daxil Ol',
    'auth.registerBtn': 'Qeydiyyatdan Keç',
    'auth.noAccount': 'Hesabınız yoxdur?',
    'auth.haveAccount': 'Artıq hesabınız var?',
    'auth.registerLink': 'Qeydiyyatdan keçin',
    'auth.loginLink': 'Daxil olun',
    'auth.wrongCredentials': 'E-poçt və ya şifrə yanlışdır.',
    'account.user': 'İstifadəçi',
    'account.logout': 'Çıxış',
    'account.myReservations': 'Rezervasiyalarım',
    'account.profileInfo': 'Profil Məlumatları',
    'account.noReservation': 'Rezervasiya tapılmadı',
    'account.noReservationDesc': 'Hələ heç bir rezervasiyanız yoxdur.',
    'account.searchTour': 'Tur axtar',
    'account.personalInfo': 'Şəxsi Məlumatlar',
    'account.edit': 'Redaktə et',
    'account.cancel': 'Ləğv et',
    'account.save': 'Saxla',
    'account.saving': 'Saxlanır...',
    'account.emailLabel': 'E-poçt',
    'account.fullName': 'Ad Soyad',
    'account.enterName': 'Adınızı daxil edin',
    'account.phone': 'Telefon',
    'account.birthDate': 'Doğum Tarixi',
    'account.passport': 'Pasport Nömrəsi',
    'account.notEntered': 'Daxil edilməyib',
    'account.loading': 'Yüklənir...',
    'account.tour': 'Tur',
    'account.hotel': 'Otel',
    'account.flight': 'Uçuş',
    'account.confirmed': 'Təsdiqləndi',
    'account.pending': 'Gözləmədə',
    'account.cancelled': 'Ləğv edildi',
    'account.persons': 'nəfər',
    'account.orderedOn': 'tarixində sifariş verildi',
    'checkout.title': 'Rezervasiya',
    'checkout.back': 'Geri',
    'checkout.flightSummary': 'Uçuş Məlumatı',
    'checkout.directFlight': 'Birbaşa Uçuş',
    'checkout.stops': 'Dayanacaq',
    'checkout.passengerInfo': 'Sərnişin Məlumatları',
    'checkout.firstName': 'Ad',
    'checkout.firstNamePlaceholder': 'Adınız',
    'checkout.lastName': 'Soyad',
    'checkout.lastNamePlaceholder': 'Soyadınız',
    'checkout.email': 'E-poçt',
    'checkout.phone': 'Telefon',
    'checkout.birthDate': 'Doğum Tarixi',
    'checkout.gender': 'Cins',
    'checkout.selectGender': 'Seçin',
    'checkout.male': 'Kişi',
    'checkout.female': 'Qadın',
    'checkout.nationality': 'Vətəndaşlıq',
    'checkout.nationalityPlaceholder': 'Azərbaycan',
    'checkout.passportNo': 'Pasport No',
    'checkout.emailPlaceholder': 'nümunə@email.com',
    'checkout.priceSummary': 'Qiymət Xülasəsi',
    'checkout.baseFare': 'Bilet Qiyməti',
    'checkout.taxes': 'Vergilər',
    'checkout.serviceFee': 'Xidmət Haqqı',
    'checkout.total': 'Cəmi',
    'checkout.payNow': 'Ödəniş Et',
    'checkout.processing': 'İşlənir...',
    'checkout.securePayment': '256-bit SSL ilə təhlükəsiz ödəniş',
    'checkout.required': 'Bu sahə məcburidir',
    'checkout.invalidEmail': 'Düzgün e-poçt ünvanı daxil edin',
    'checkout.noFlight': 'Uçuş Tapılmadı',
    'checkout.noFlightDesc': 'Zəhmət olmasa uçuş axtarışına qayıdın və uçuş seçin.',
    'checkout.backToSearch': 'Axtarışa Qayıt',
    'checkout.successTitle': 'Rezervasiyanız Tamamlandı!',
    'checkout.successDesc': 'Biletiniz uğurla yaradıldı.',
    'checkout.reservationNo': 'Rezervasiya No',
    'checkout.route': 'Marşrut',
    'checkout.passenger': 'Sərnişin',
    'checkout.emailSent': 'Bilet detalları e-poçt ünvanınıza göndərildi:',
    'checkout.backToHome': 'Ana Səhifəyə Qayıt',
    'checkout.hotelSummary': 'Otel Məlumatları',
    'checkout.nights': 'gecə',
    'checkout.guests': 'Qonaqlar',
    'checkout.guestInfo': 'Qonaq Məlumatları',
    'checkout.guestN': 'Qonaq',
    'checkout.noBooking': 'Rezervasiya Tapılmadı',
    'checkout.noBookingDesc': 'Zəhmət olmasa geri qayıdın və seçim edin.',
    'checkout.hotelSuccessDesc': 'Otel rezervasiyanız uğurla yaradıldı.',
    'checkout.hotel': 'Otel',
    'checkout.checkIn': 'Giriş',
    'checkout.checkOut': 'Çıxış',
    'filter.stops': 'Ötürmələr',
    'filter.allFlights': 'Bütün uçuşlar',
    'filter.oneStop': '1 Ötürmə',
    'filter.directFlight': 'Birbaşa uçuş',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'az';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
